#!/usr/bin/env node
/**
 * Generate src/lib/logos.ts from simple-icons.
 *
 * simple-icons stays a devDependency and never reaches the browser: this writes
 * out only the paths actually used, which is a few hundred bytes rather than a
 * 3,461-icon package. Re-run it after changing the skill list.
 *
 * Marks are CC0. Two deliberate absences: Amazon and OpenAI are not in the set
 * — both restrict use of their marks — so those skills render as text, which is
 * the correct outcome rather than a gap to work around.
 *
 * usage: node scripts/generate-logos.mjs
 */
import { writeFileSync } from "node:fs";
import * as si from "simple-icons";

/** Skill label as it appears in the marquee → simple-icons slug. */
const MAP = {
  TypeScript: "typescript",
  React: "react",
  "Next.js": "nextdotjs",
  "Node.js": "nodedotjs",
  "Tailwind CSS": "tailwindcss",
  Zod: "zod",
  "Vue.js": "vuedotjs",
  PHP: "php",
  Python: "python",
  MySQL: "mysql",
  PostgreSQL: "postgresql",
  MongoDB: "mongodb",
  Redis: "redis",
  WordPress: "wordpress",
  Vercel: "vercel",
  Docker: "docker",
  Cloudflare: "cloudflare",
  "GitHub Actions": "githubactions",
  Jest: "jest",
  Lighthouse: "lighthouse",
  Claude: "anthropic",
};

const key = (slug) => "si" + slug.charAt(0).toUpperCase() + slug.slice(1);

const entries = [];
for (const [label, slug] of Object.entries(MAP)) {
  const icon = si[key(slug)];
  if (!icon) throw new Error(`simple-icons has no "${slug}" — check the slug`);
  entries.push([label, icon.path]);
}

const body = entries
  .map(([label, path]) => `  ${JSON.stringify(label)}: ${JSON.stringify(path)},`)
  .join("\n");

writeFileSync(
  "src/lib/logos.ts",
  `/**
 * Brand marks, keyed by the skill label they belong to.
 *
 * GENERATED by scripts/generate-logos.mjs — do not edit by hand. Paths are from
 * simple-icons (CC0), which is a devDependency: only these paths ship, not the
 * package.
 *
 * Every mark is a single path on a 24x24 viewBox and inherits currentColor, so
 * the strip stays monochrome in both themes. A skill with no entry here renders
 * as its label alone, which is what Amazon and OpenAI do — neither permits
 * redistribution of its mark.
 */
export const LOGOS: Record<string, string> = {
${body}
};
`,
);

console.log(`wrote src/lib/logos.ts — ${entries.length} marks`);
